ClubFutbol/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('ClubFutbolApp.urls', 'ClubFutbolApp'))),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ClubFutbolApp/urls.py
from django.conf.urls import url
from django.urls import path
from ClubFutbolApp import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    path('', Inicio.as_view(), name="index"),
    path('registro/', registro, name="registro"),
    #path('jugadores/', Jugadores.as_view(), name="jugadores"),
    path('jugadores/<int:pk>', Jugadores.as_view(), name="jugadores"),
    path('crear_jugador/', login_required(crearJugador.as_view()), name="crear_jugador"),
    path('est_jugadores/<int:pk>/', estJugador.as_view(), name="est_jugadores"),
    path('equipos/', Equipos.as_view(), name="equipos"),
    path('equipos/<str:pk>', Equiposfil.as_view(), name="Equiposfil"),
    path('crear_equipo/', login_required(crearEquipo.as_view()), name="crear_equipo"),
    path('crear_partido/', login_required(crearPartido.as_view()), name="crear_partido"),
    path('est_equipo/<int:pk>/', estPartido.as_view(), name="est_equipo"),
    path('partidos/<int:pk>/', listaPartidos.as_view(), name="partidos"),
    path('crear_est_partido/', crearEstPartido.as_view(), name="crear_est_partido"),
    path('editar_est_partido/<int:pk>', editarEstPartido.as_view(), name="editar_est_partido"),
    
    

]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ClubFutbolApp/models.py
from django.db import models

# Create your models here.

class Club(models.Model):
    club_nombre = models.CharField(max_length=30)
    direccion = models.CharField(max_length=30)
    ciudad = models.CharField(max_length=30)
    email = models.EmailField()
    telefono = models.IntegerField()
    imagen = models.ImageField(upload_to='ClubFutbolApp', null=True, blank=True)

    class Meta:
        verbose_name ='club'
        verbose_name_plural ='clubs'

    def __str__(self):
        return self.club_nombre

class Categoria(models.Model):
    cat_nombre = models.CharField(max_length=20)

    class Meta:
        verbose_name ='categoria'
        verbose_name_plural ='categorias'

    def __str__(self):
        return self.cat_nombre

class Equipo(models.Model):
    equipo_nombre = models.CharField(max_length=30)
    club = models.ForeignKey(Club, on_delete = models.CASCADE)
    entrenador = models.CharField(max_length=30)
    categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)

    class Meta:
        verbose_name ='equipo'
        verbose_name_plural ='equipos'

    def __str__(self):
        return self.equipo_nombre



class Posicion(models.Model):
    pos_nombre = models.CharField(max_length=20)

    class Meta:
        verbose_name ='posicion'
        verbose_name_plural ='posiciones'

    def __str__(self):
        return self.pos_nombre

class Jugador(models.Model):
    jug_nombre = models.CharField(max_length=30)
    image = models.ImageField(upload_to='Jugadores', null=True, blank=True)
    fecha_nacimiento = models.DateField()
    dorsal = models.IntegerField()
    posicion = models.ForeignKey(Posicion, on_delete = models.CASCADE)
    equipo = models.ForeignKey(Equipo, on_delete = models.CASCADE)

    class Meta:
        ordering = ["equipo", "jug_nombre"]
        verbose_name ='jugador'
        verbose_name_plural ='jugadores'

    def __str__(self):
        return "%s-%s" %(self.equipo,self.jug_nombre)

class Partido(models.Model):
    OPCIONES_DE_LUGAR = ('Casa', 'Casa'), ('Fuera', 'Fuera')
    fecha = models.DateTimeField()
    n_jornada = models.IntegerField(max_length=2)
    equipo = models.ForeignKey(Equipo, on_delete = models.CASCADE)
    rival = models.CharField(max_length=30)
    campo = models.CharField(max_length=5, choices = OPCIONES_DE_LUGAR, blank=True, null=True)
    resultado_equipo = models.PositiveSmallIntegerField(default=0)
    resultado_rival = models.PositiveSmallIntegerField(default=0)

    class Meta:
        ordering = ["fecha", "equipo"]
        verbose_name ='partido'
        verbose_name_plural ='partidos'

    def __str__(self):
        return "%s-%s" %(self.equipo,self.rival)
   

class DatosPartido(models.Model):
    #OPCIONES_DE_TITULAR = ('True', 'Titular'), ('False', 'Suplente')
    partido = models.ForeignKey(Partido, on_delete = models.CASCADE)
    jugador_convocado = models.ForeignKey(Jugador, on_delete = models.CASCADE)
    titular = models.BooleanField(blank=True, null=True)
    minutos_jugados = models.IntegerField()
    goles = models.IntegerField(default=0)

    class Meta:
        ordering = ["jugador_convocado"]
        verbose_name ='datospartido'
        verbose_name_plural ='datospartidos'
        

ClubFutbolApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username', "first_name", "last_name", "email", "password1", "password2"]
        
class JugadoresForm(forms.ModelForm):
    class Meta:
        model = Jugador
        fields = ['jug_nombre', 'fecha_nacimiento', 'dorsal', 'posicion', 'equipo', 'image']

class EquipoForm(forms.ModelForm):
    class Meta:
        model = Equipo
        fields = ['equipo_nombre', 'club', 'entrenador', 'categoria']
    
class PartidoForm(forms.ModelForm):
    
    class Meta:
        model = Partido
        fields = ['campo', 'fecha', 'n_jornada', 'equipo', 'rival', 'fecha', 'resultado_equipo', 'resultado_rival']
        widgets = {
            'fecha': forms.DateInput(format=('%d/%m/%Y'), attrs={'type': 'date'}),
        }

class EstPartidoForm(forms.ModelForm):

    class Meta:
        model = DatosPartido
        fields = ['jugador_convocado', 'partido', 'titular', 'minutos_jugados', 'goles']
       
   

ClubFutbolApp/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.views.generic import TemplateView, ListView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login
from django.contrib import messages
from .models import *
from .forms import *


class Inicio(LoginRequiredMixin, TemplateView):
    template_name= 'ClubFutbolApp/Home.html'

class Jugadores(ListView):
    model= Jugador
    template_name='ClubFutbolApp/jugadores.html'
    context_object_name='jugadores'
    def get_queryset(self):
        qs=super(Jugadores, self).get_queryset()
        return qs.filter(equipo=self.request.resolver_match.kwargs['pk'])

class crearJugador(CreateView):
    model= Jugador
    template_name= 'ClubFutbolApp/crear_jugador.html'
    form_class= JugadoresForm
    success_url= '/equipos'

class estJugador(ListView):
    model= DatosPartido
    template_name='ClubFutbolApp/est_jugadores.html'
    context_object_name='datospartidos'
    
    def get_queryset(self):
        qs=super(estJugador, self).get_queryset()
        return qs.filter(jugador_convocado=self.request.resolver_match.kwargs['pk'])

class crearEquipo(CreateView):
    model= Equipo
    template_name= 'ClubFutbolApp/crear_equipo.html'
    form_class= EquipoForm
    success_url= '/equipos'

class Equipos(ListView):
    model= Equipo
    template_name='ClubFutbolApp/equipos.html'
    context_object_name='equipos'
    queryset= Equipo.objects.all()

class Equiposfil(ListView):
    model= Equipo
    template_name='ClubFutbolApp/equipos.html'
    context_object_name='equipos'
    #queryset= Equipo.objects.all()
    def get_queryset(self):
        qs=super(Equiposfil, self).get_queryset()
        return qs.filter(equipo_nombre__icontains=self.request.resolver_match.kwargs['pk'])

class crearPartido(CreateView):
    model= Partido
    template_name= 'ClubFutbolApp/crear_partido.html'
    form_class= PartidoForm
    success_url= '/equipos'

class listaPartidos(ListView):
    model= Partido
    template_name='ClubFutbolApp/partidos.html'
    context_object_name='partidos'
    #queryset= Partido.objects.all()
    
    def get_queryset(self):
        qs=super(listaPartidos, self).get_queryset()
        return qs.filter(equipo=self.request.resolver_match.kwargs['pk'])

class crearEstPartido(CreateView):
    model= DatosPartido
    template_name= 'ClubFutbolApp/crear_est_partido.html'
    form_class= EstPartidoForm
    success_url= '/equipos'

class editarEstPartido(UpdateView):
    model= DatosPartido
    template_name= 'ClubFutbolApp/crear_est_partido.html'
    form_class= EstPartidoForm
    success_url= '/equipos'


class estPartido(ListView):
    model= DatosPartido
    template_name='ClubFutbolApp/est_equipo.html'
    context_object_name='datospartidos'
    
    def get_queryset(self):
        qs=super(estPartido, self).get_queryset()
        return qs.filter(partido=self.request.resolver_match.kwargs['pk'])

def registro(request):
    data = {
        'form': CustomUserCreationForm()
    }

    if request.method == "POST":
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            return redirect(to="/")
        data["form"] = formulario


    return render(request, 'registration/registro.html', data)

    

templates/ClubFutbolApp/Home2.html
{% extends "ClubFutbolApp/base.html" %}
{% load static %}


<!DOCTYPE html>
{% block content %}
<html>
 <h1>prueba</h1>
</html>
{% endblock %}

templates/ClubFutbolApp/base.html
<html>

<head>

    {% load static %}


    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mio2.css' %}" rel="stylesheet">

    

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     

    <!-- Styles -->
    <!-- <link href="{% static 'users/css/gestion.css' %}" rel="stylesheet"> -->
</head>

<body>
  {% if user.is_authenticated %}
      
  <li style="text-align: right;">
    <a href="{% url 'logout' %}" style="color: rgb(12, 6, 1);" >cerrar sesión {{request.user.username.capitalize}}</a> 
  </li>
  {% else %}
  <li>
    <a ></a> 
  </li>
  {% endif %}
  
 
{% block barra %}   
 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!---<li class="navbar-brand {% if request.path == '/jugadores/' %}active{% endif %} px-lg-4">
        <a class="nav-link" href="/jugadores">Jugadores<span class="sr-only">(current)</span></a>
      </li>-->
      <!---<li class="navbar-brand {% if request.path == '/crear_jugador/' %}active{% endif %} px-lg-4">
        <a class="nav-link" href="/crear_jugador">Crear Jugador<span class="sr-only">(current)</span></a>
      </li>-->
      <li class="navbar-brand {% if request.path == '/equipos/' %}active{% endif %} px-lg-4">
        <a class="nav-link" href="/equipos">Equipos<span class="sr-only">(current)</span></a>
      </li>
      {% if perms.ClubFutbolApp.add_equipo %}
      <li class="navbar-brand {% if request.path == '/crear_equipo/' %}active{% endif %} px-lg-4">
        <a class="nav-link" href="/crear_equipo">Crear Equipo<span class="sr-only">(current)</span></a>
      </li>
      {% endif %}
      
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
  {% endblock barra %}
 

 {% block content %}

 {% endblock %}


    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        
        
        <p class="m-0 mbt1">&copy; ClubFutbolApp</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'ClubFutbolApp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'ClubFutbolApp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

templates/ClubFutbolApp/crear_equipo.html
{% extends "ClubFutbolApp/Home.html" %}
{% load static %}


{% block contenido %}


<div class="container">
    <div class="contenedorFormulario" class="table-responsive">
    <form  enctype="multipart/form-data"  method="POST">
        <table>{{ form }}</table>
        {% csrf_token %}
   
    
    
    <button type="submit" style="cursor: pointer;" class="btn btn-light">Crear/Editar</button>
    <button type="submit" style="cursor: pointer; " class="btn btn-light"><a href= "/equipos" style="color: rgb(17, 11, 6);">Cancelar</a></button>
</form>
</div>
</div>  


{% endblock %}

templates/ClubFutbolApp/crear_est_partido.html
{% extends "ClubFutbolApp/Home.html" %}
{% load static %}


{% block contenido %}

<div class="container">
<div class="contenedorFormulario" class="table-responsive">
    <form  enctype="multipart/form-data"  method="POST">
        <table class="table table-hover">

            <td>{{ form }}</td>

        </table>
        {% csrf_token %}
   
    
    
    <button type="submit" style="cursor: pointer;" class="btn btn-light">Crear/Editar</button>
    <button type="submit" style="cursor: pointer; " class="btn btn-light"><a href= "/equipos" style="color: rgb(8, 4, 0);">Cancelar</a></button>
</form>
</div>
</div>



{% endblock %}

templates/ClubFutbolApp/crear_jugador.html
{% extends "ClubFutbolApp/Home.html" %}
{% load static %}


{% block contenido %}


<div class="container">
    <div class="contenedorFormulario" class="table-responsive">
    <form  enctype="multipart/form-data"  method="POST">
        <table class="table table-hover">{{ form }}</table>
        {% csrf_token %}
   
    
    
    <button type="submit" style="cursor: pointer;" class="btn btn-light">Crear/Editar</button>
    <button type="submit" style="cursor: pointer; " class="btn btn-light"><a href= "/equipos" style="color: rgb(7, 3, 1);">Cancelar</a></button>
</form>
</div>
</div>  



{% endblock %}

templates/ClubFutbolApp/crear_partido.html
{% extends "ClubFutbolApp/Home.html" %}
{% load static %}


{% block contenido %}

<div class="container">
<div class="contenedorFormulario" class="table-responsive">
    <form enctype="multipart/form-data" method="POST">
        <table class="table table-hover">
            <tr>
                <td>Campo:</td> <td>{{ form.campo }}</td>
            </tr>
            <tr><td>Fecha:</td> <td>{{ form.fecha }}</td></tr>
            <tr><td>Jornada:</td> <td>{{ form.n_jornada }}</td></tr>
            <th colspan="2">Resultado:</th>
            <tr><td>{{ form.equipo }}</td><td>{{ form.resultado_equipo }}</td></tr>
            <tr><td>{{ form.rival }}</td><td>{{ form.resultado_rival }}</td></tr>
            
        {% csrf_token %}
    </table>
    
    
    <button type="submit" style="cursor: pointer;" class="btn btn-light">Crear/Editar</button>
    <button type="submit" style="cursor: pointer; " class="btn btn-light"><a href= "/equipos" style="color: rgb(8, 4, 0);">Cancelar</a></button>
</form>
</div>
</div>



{% endblock %}

templates/ClubFutbolApp/equipos.html
{% extends "ClubFutbolApp/Home.html" %}
{% load static %}

{% block contenido %}

<html>

<div class="contenedorFormulario" class="table-responsive" class="hero-container" data-aos="fade-in">
    
         <table class="table table-hover">
            <tfoot><button type="button" class="btn btn-light"><a href="/crear_equipo" style="color: black;">Crear Equipo</a></button></tfoot>
            <thead> 
                <tr>
                    <th scope="col">Equipo</th>
                    <th scope="col">Club</th>
                    <th scope="col">Entrenador</th>
                    <th scope="col">Categoria</th>
                    <th scope="col"></th>
                    
                    
                </tr>
            </thead>
        {% for e in equipos %}
            <tbody>
                <tr>
                    <td>{{ e.equipo_nombre }}</td>
                    <td>{{ e.club }}</td>
                    <td>{{ e.entrenador }}</td>
                    <td>{{ e.categoria }}</td>
                    <td><button class="btn btn-light"><a href="/jugadores/{{ e.id }}" style="color: rgb(14, 9, 2);">Plantilla</a></button></td>
                    <td><button class="btn btn-light"><a href="/partidos/{{ e.id }}" style="color: rgb(14, 9, 2);">Partidos</a></button></td>
                   
                </tr>
            </tbody>
        {% endfor %}
     
    </table>
     
</div>

</html>

{% endblock contenido %}

templates/ClubFutbolApp/est_equipo.html
{% extends "ClubFutbolApp/Home.html" %}
{% load static %}

<!DOCTYPE html>
{% block contenido %}
<html>
 
<div class="contenedorFormulario" class="table-responsive">
    
    
{% if datospartidos %}
    <table class="table table-hover">
        <thead>
            <th style="color: rgb(8, 4, 1); height: 60px ; width: 50%;" class="col-xs-12 col-md-8" >
                {% for datospartido in datospartidos %}
                    {% if forloop.first %}
                        <a>{{ datospartido.partido.equipo|upper }} contra
                        {{ datospartido.partido.rival|upper }}
                        </a>
                    {% endif %}
                {% endfor %}
            </th>
            <tr>
            
                <th>Jugadores</th>
                <th>Titular</th>
                <th>Min. Jugados</th>
                <th>Goles</th>
            
            </tr>
        </thead>
    <tbody>
        
        {% for datospartido in datospartidos %}
            
            <tr>
            
                <td width="25%">{{ datospartido.jugador_convocado.jug_nombre }} </td>
                {% if datospartido.titular == True %}
                        <td>Si</td>
                    {% else %}
                        <td>No</td>
                    {% endif %}
                <td width="25%">{{ datospartido.minutos_jugados }} </td>
                <td >{{ datospartido.goles }} </td>
                
            </tr>

        {% endfor %}
           
    </tbody>
    </table>

{% else %}
<h1 style="color: rgb(15, 7, 1); text-align: center;">Este equipo todavia no ha jugado ningún partido</h1>
{% endif %}
        </div>

     </div>
    </table>
     
</div>

</html>
{% endblock contenido %}

templates/ClubFutbolApp/est_jugadores.html
{% extends "ClubFutbolApp/Home.html" %}
{% load static %}


<!DOCTYPE html>
{% block contenido %}
<html>
 
<div class="contenedorFormulario" class="table-responsive" >
  
{% if datospartidos %}
<table class="table table-hover">
    <thead>
        <th style="color: rgb(10, 5, 1); align-content: right;">
            {% for datospartido in datospartidos %}
                {% if forloop.first %}
                    {{ datospartido.jugador_convocado.dorsal }}-
                    {{ datospartido.jugador_convocado|upper }}
                    <td><button class="btn btn-light"><a href="/crear_est_partido/" style="color: rgb(14, 8, 1);">Introducir datos partido</a></button></td>
                    
                {% endif %}
            {% endfor %}
        </th>
        <tr>
            
            <th>Partido</th>
            <th>Min. Jugados</th>
            <th>Titular</th>
            <th>Goles</th>
        
        </tr>
    </thead>
    <tbody>
        
        {% for datospartido in datospartidos %}
            
            <tr>
                {% if datospartido.partido.campo == "Casa" %}             
                    <td><a>{{ datospartido.partido.equipo|upper }} {{ datospartido.partido.resultado_equipo }} - {{ datospartido.partido.resultado_rival }} {{ datospartido.partido.rival|upper }}  </a></td>
                {% else %} 
                    <td><a>{{ datospartido.partido.rival|upper }} {{ datospartido.partido.resultado_rival }} - {{ datospartido.partido.resultado_equipo }} {{ datospartido.partido.equipo|upper }} </a></td> 
                {% endif %}
                
                <td >{{ datospartido.minutos_jugados }} </td>
                
                    {% if datospartido.titular == True %}
                        <td>Si</td>
                    {% else %}
                        <td>No</td>
                    {% endif %}
                <td >{{ datospartido.goles }} </td>
                
                <tr>
                    
                    {% if forloop.first %}
                        {% if datospartido.jugador_convocado.image %}
                            <img src="{{ datospartido.jugador_convocado.image.url }}" style="max-width: 100px;"> 
                        {% else %}
                        <img src="{% static 'noImagen.jpg' %}" style="max-width: 100px;"> 
                        {% endif %}
                    {% endif %}
                </tr>
                   
            </tr>

        {% endfor %}
           
    </tbody>
</table>

{% else %}
<td><button class="btn btn-light"><a href="/crear_est_partido" style="color: rgb(14, 8, 1);">Introducir datos partido</a></button></td>
<table class="contenedorFormulario" class="table table-hover">
<th style="color: rgb(15, 7, 1);text-align: center;" >Este jugador no tiene todavía estadisticas</th>
</table>
{% endif %}
        </div>

     </div>
    </table>
     
</div>

</html>
{% endblock contenido %}

templates/ClubFutbolApp/jugadores.html
{% extends "ClubFutbolApp/Home.html" %}
{% load static %}


<!DOCTYPE html>
{% block contenido %}


<html>
 
<div class="contenedorFormulario" class="table-responsive">
    
         <table class="table table-hover">
            <thead> 
              <th><button type="button" class="btn btn-light"><a href="/crear_jugador" style="color: black;">Crear Jugador</a></button></th> 
              <th style="color: rgb(10, 5, 1); align-content: right;">
                {% for e in jugadores %}
                    {% if forloop.first %}
                        {{ e.equipo|upper }}
                    {% endif %}
                {% endfor %}
                </th>
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Dorsal</th>
                    <th scope="col">Posición</th>
                   
                    <th scope="col">Foto</th>
                    <th scope="col">Datos</th>

                </tr>
            </thead>
        {% for j in jugadores %}
            <tbody>
                <tr>
                    <td>{{ j.jug_nombre }}</td>
                    <td>{{ j.dorsal }}</td>
                    <td>{{ j.posicion }}</td>
                    
                    {% if j.image %}
                        <td><img src="{{ j.image.url }}" style="max-width: 60px;"></td>
                    {% else %}
                        <td><img src="{% static 'noImagen.jpg' %}" style="max-width: 100px;"></td>
                    {% endif %}
                    <td><button class="btn btn-light"><a href="/est_jugadores/{{ j.id }}" style="color: rgb(14, 8, 1);">Estadisticas</a></button></td>
                    <!--<td><a href="/est_equipo/{{ j.equipo_id }}" style="color: rgb(14, 8, 1);">Estadistica equipo</a></td>-->
                    
           

                </tr>
            </tbody>
        {% endfor %}
     
    </table>
     
</div>

</html>
{% endblock contenido %}

templates/ClubFutbolApp/partidos.html
{% extends "ClubFutbolApp/Home.html" %}
{% load static %}

<!DOCTYPE html>
{% block contenido %}
<html>
 
<div class="contenedorFormulario" class="table-responsive">
    
    
{% if partidos %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Partidos</th>
            </tr>        
        </thead>

        {% for e in partidos %}
            <tbody> 
            {% if e.campo == "Casa" %}             
                <td><a>Jornada {{ e.n_jornada }}. {{ e.equipo|upper }} {{ e.resultado_equipo }} - {{ e.resultado_rival }} {{ e.rival|upper }}  </a></td>
            {% else %} 
            <td><a>Jornada {{ e.n_jornada }}. {{ e.rival|upper }} {{ e.resultado_rival }} - {{ e.resultado_equipo }} {{ e.equipo|upper }} </a></td> 
            {% endif %}
            <td><button type="button" class="btn btn-light"><a href="/est_equipo/{{ e.id }}" style="color: black;">Datos del partido</a></button></td>
            
        {% endfor %}
            </tbody>      
        <tfoot><button type="button" class="btn btn-light"><a href="/crear_partido" style="color: black;">Crear Partido</a></button></tfoot>    
      
    </table>

{% else %}
<tfoot><button type="button" class="btn btn-light"><a href="/crear_partido" style="color: black;">Crear Partido</a></button></tfoot>
<h1 style="color: rgb(15, 7, 1); text-align: center;">Este equipo todavia no ha jugado ningún partido</h1>

{% endif %}
        


     </div>
    </table>



</html>
{% endblock contenido %}